### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by arthurbenemann** [DroidPlanner/droidplanner#1054]
Add the possibility to flash the pixhawk via DroidPlanner. Two constrains that should help are:
* Pixhawk only
* direct USB connection only

**Comment by phmagic** [comment]
I propose we move this to a Preflight app.

**Comment by Thalek** [comment]
I like that idea.  Then if there are significant differences in say, UAVs and rovers, there'd be plenty of room to add the changes without bloating the main app.

**Comment by ne0fhyk** [comment]
Moved to the preflight issue list: https://github.com/DroidPlanner/DP-Preflight-Config/issues/2
