### ISSUE TITLE
UI Editor - add/insert waypoints after selected waypoint

### ISSUE THREAD

**Issue by keyoss** [DroidPlanner/droidplanner#1122]
![screenshot_2014-10-03-13-45-54](https://cloud.githubusercontent.com/assets/8471059/4505398/e0649902-4af3-11e4-8217-d9a635982d6b.png)

problem:
if i plan a mission and have the Land position set, i can not add a waypoint directly after waypoint 17 but before 18, in this case.

nice case:
if i select a waypoint, it should be possible to 'insert' waypoints in between them. 
lets say, i want to add between 17 and 18. i select 17, hit add waypoint (+) and it should be placed between 17 and 18, respecting the flightpath, just like you insert/divide the spline. if i want to relocate the 'new number 18' the user could still hold and drag the wp to the desired location. the old land wp (18) is then renamed to 19.... etc pp

i know adding wp is not possible if a land is defined, but this should be changed too imho.

**Comment by ne0fhyk** [comment]
Merged into #1356
