### ISSUE TITLE
Survey: Camera coverage and area calculatios are wrong.

### ISSUE THREAD

**Issue by AndKe** [DroidPlanner/droidplanner#1320]
please see screenshot: https://www.dropbox.com/s/jpy2tnj45j90gy3/tempFileForShare.jpg?dl=0
S100 comes with a focal length of 24mm (36mm eqivalent)
by my calculations, this mean each photo taken at 100mAGL covers 150x100meters.
This gives a pixel length/height (GSD)of 3.75cm  , and the pixel area (usually NOT of any interest) would be 7.2cm2
GSD stands for ground sampling *distance*  a lenght/width of a pixel - not area.
The reason we care for GSD, is that woth proper processing, the calculated elevation error is less than 2.5*x pixel size.

Finally, the area calculation, of 28km2  - is extremely wrong.

**Comment by ne0fhyk** [comment]
Merged into #1356
