### ISSUE TITLE
Built-In camera profiles for GoPro broken

### ISSUE THREAD

**Issue by chriselsen** [DroidPlanner/droidplanner#1328]
The built-in camera profiles seem to be broken. 

This is a survey mission with the built-in GoPro Hero3+ Black settings:
![screenshot_2014-12-14-16-12-15](https://cloud.githubusercontent.com/assets/5304256/5429726/8b13373c-83ac-11e4-9170-e87dd8c49870.png)

And this is the same mission using a custom camera setting and using this exact file (https://github.com/DroidPlanner/droidplanner/blob/master/Android/assets/CameraInfo/GoPro%20Hero%203%2B%20Black.xml):
![screenshot_2014-12-14-16-12-07](https://cloud.githubusercontent.com/assets/5304256/5429728/bc686ff0-83ac-11e4-8850-7b950c655e23.png)

Altitude, Hatch Angle, Overlap and Sidelap are equal in both missions. 
And in theory my manual settings should be equivalent to the built-in ones. But they are obviously not:

Droidplanner version: 2.8.6 RC3
But the problem also exists in other versions

**Comment by phmagic** [comment]
@chriselsen can you check with the latest Droidplanner to see if this was fixed?
