### ISSUE TITLE
DroidPlanner 3 name change: Tower

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/droidplanner#1344]
Hi all, we're considering a name change for the DroidPlanner app for the Version 3 release.
As of now, the new name under consideration is **Tower** (as in control tower).

**Comment by zumbrunnen** [comment]
Hi and happy new year everybody! :tada: :confetti_ball: :fireworks: 

I've just created a form to send in name suggestions until Jan 5th EOD (UTC).

Here's the link: http://goo.gl/H5zn4T

On Jan 6th, I'm going to set up a poll. So everybody can vote for their favorite name. After Jan 10th, I'll publish the results. Maybe this let's us agree on the best name! :wink:

**Comment by Craig3DRobotics** [comment]
How about we call it "Squilter"?  It rolls off the tongue and at least it is unique

**Comment by squilter** [comment]
@Craig3DRobotics You have my vote!

**Comment by Thalek** [comment]
[grin]  Squilter, or perhaps Benneman.

**Comment by Craig3DRobotics** [comment]
I guess AB BA is already taken.

Maybe Benne

Benne Squilter BS???  nah probably not.

**Comment by azrin1972** [comment]
How about AVeCC - Autonomous Vehicle Command Center

**Comment by zumbrunnen** [comment]
Hi @azrin1972 

Feel free to add your suggestion here: http://goo.gl/H5zn4T

**Comment by azrin1972** [comment]
Done :)

**Comment by zumbrunnen** [comment]
Hey everybody!

Here's a list of all the submitted propositions (in alphabetic order), including their taglines: http://goo.gl/P2N9MN

And finally, **the poll**: :loudspeaker: http://goo.gl/n7mrVm :loudspeaker: 

I'll close the poll on Jan 10th, EOD (UTC) and the results will then be published.

Happy voting! :ballot_box_with_check: :shipit: 

Advertisement: My suggestion, and still my favorite, is `3DR Mission Control`.

**Comment by bys1123** [comment]
3DR Mission Control is much better than Tower. :+1:

**Comment by zumbrunnen** [comment]
Hello there!

I've closed the poll and here are the results (Top 3):

1. DroidPlanner (27 votes, 28%)
2. Tower - Mission Control for Drones (23 votes, 24%)
3. 3DR Mission Control (16 votes, 17%)

Here's the full list:

![poll_results](https://cloud.githubusercontent.com/assets/3499909/5695076/3c064f2e-998e-11e4-94a9-5e84eb298b72.png)

It seems, most people do not want a name change and stick to good, old "DroidPlanner". To highlight the connection to 3DR Robotics and the bundle with "3DR Services", one could also call the app "3DR DroidPlanner".

**Comment by ne0fhyk** [comment]
@zumbrunnen thanks for the update!

While keeping **DroidPlanner** as the name would be the most convenient, and from the polls, the most favored option, the issues I highlighted above (i.e: possible trademark issue) makes that not a good option.

As such, based on the polls, we'll go with **Tower** as the new name for the app.

The next beta release will be updated with the app new name!

**Comment by ThorstenDP** [comment]
Well, if you sum 
- 3DR mission control
- and APM mission control
and concerning the fact that the "Tower" suggestion also contains "Mission Control", I suggest a runoff poll between
- Tower
- and Mission Control 

The problem I have with tower is that it is pretty focussed to planes and copters - not rovers or boat. Mission Control is more neutral.

My 2 cents...
Cheers,
Thorsten

**Comment by MJBeaubien** [comment]
I agree, let there be a runoff.

**Comment by Craig3DRobotics** [comment]
Makes sense to have a final vote.

**Comment by ne0fhyk** [comment]
@ThorstenDP @MJBeaubien thanks for the suggestions, but this is good enough, otherwise we would be making runoff polls ad-infinitum.

**Comment by ThorstenDP** [comment]
@ne0fhyk with only 2 candidates?

**Comment by zumbrunnen** [comment]
I agree with @ThorstenDP about the "aircraft only" problem. Shall I initiate a final voting or does someone else want to take over?

If 3DR is going to take over the software (and maybe even wants to close-source it [see https://plus.google.com/100816418778306854164/posts/Xc6wpg9Amts]) they gonna chose the name of their choice anyway. :pensive: 

@ne0fhyk I don't think an acronym composed of "Droid" (which is a short version of android) will run into legal issues. There are a lot of trademarks and other trademarks that include the latter. E.g.:
 * DROID (TM by Lucas Arts) and DROIDBOOK, JOBDROID, DROIDTOUCH, ...
 * JAVA (TM by Oracle) and JAVAMILL, JAVAWRAP, JAVA SURF, ...

See [TESS](http://tmsearch.uspto.gov/bin/gate.exe?f=login&p_lang=english&p_d=trmk) for other examples.

And last but not least: And why the heck does 3D Robotics list DroidPlanner with a Trademark-sign on its web page? 

![dptm](https://cloud.githubusercontent.com/assets/3499909/5697177/3af7f1e4-99ea-11e4-9502-75c0d79a8787.png)

http://3drobotics.com/landing-software/

**Comment by ne0fhyk** [comment]
@ThorstenDP quick clarification, @phmagic's response on the link you posted above only meant that 3DR Services supports any type of front end, no matter the license. So an open or closed source GCS or other front ends can be built on top of it.

DroidPlanner is **open source**, and shall remain **open source**!

**Comment by zumbrunnen** [comment]
Oh, you're right, @ne0fhyk - I should have better read that :wink:

**Comment by Thalek** [comment]
I agree that Mission Controller is less aircraft-centric than Tower. That said, the creators get to call the shots, and I abide by their decision.

**Comment by jmachuca77** [comment]
If Droidplanner was not going to be considered, then I would say lets do a runoff vote with the options that are viable. If I voted for Droidplanner, and if I had known it was not going to be used anyway, then I would have voted for something else….

**Comment by zumbrunnen** [comment]
@jmachuca77 The poll said "Please select your favorite name **and all other acceptable** suggestions." :wink: 

If nobody else is taking the initative, I'm going to create a showdown voting between "Tower" and "3DR Mission Control". I'm not yet sure about the setup, to prevent cheating :grinning: Maybe it would be a good idea to have users state their name/github account to prevent multiple submissions per person. Or: Google Forms offers the possibility to limit one vote per person - but then, every voter needs a Google account....

**Comment by ne0fhyk** [comment]
@zumbrunnen thanks for the initiative, but we'll go ahead and use **Tower** as the name for the app going forward.

**Comment by zumbrunnen** [comment]
@ne0fhyk how undemocratic... :smirk: who is "we"? 3DR?

**Comment by Thalek** [comment]
Most probably, the creator(s) of Droid Planner, and the major contributors.

**Comment by AndyLeeRobinson** [comment]
Bit late now, but my 2c...
I think Tower is an absurd and nondescriptive name for a system that facilitates the programming of series of instructions for a UAV to carry out.
Having said that, I have difficulty in thinking of an alternative name for the descriptive and now familiar DroidPlanner - and the English language can be somewhat deficient to describe something it hasn't encountered before!
One could just come up with a new word, that would be unique and grow into its definition, or one could try to make something that describes it it does with a mixture or compounds of the following words: planner, editor, compositor, programmer, sequencer, instructor, director, controller with mission, quest, journey, route, event.
Seqdir, Evplan, Uaventus, MishEd etc...

Phew... after having said that, I think "Event Horizon" may have some merit, loosely combining a sequence of events, a horizon which all UAVs use, with horizon also meaning a frontier, and event horizon for exotic physics... :-)

**Comment by ThorstenDP** [comment]
The cons (form above):
- Tower is a common word, it's hard to search on google.
- Tower" would even explain less what the app does. 
- Tower does not fully describe the functionality of the app
- 3DR Mission Control is much better than Tower. 
- "aircraft only" problem
- Tower is an absurd and non descriptive name

We have: 
Mission Controller related names:
- 3DR Control station
- 3DR Mission Control
- APM Mission Control
- Tower - Mission Control
- UAV Mission Controller

53 Votes

Tower related names
- Tower - Mission Control
- UAV Control Tower

23 Votes

For sure it is up to the devs/3DR. That's fine! But if it was decided before then why all this discussion?

**Comment by phmagic** [comment]
After polling, we've decided to go with Tower for marketing/branding reasons.  We appreciate the feedback and plan to continue to develop all of DP in an open environment.
