### ISSUE TITLE
Unable to set 'Text to Speech' language!

### ISSUE THREAD

**Issue by apocal1pse** [DroidPlanner/droidplanner#1352]
I'm using Samsung S3 and everytime I start DP I get this message and I can't ear any of the messages or warnings.

Is this a problem with S3 version?

What can I try to fix this issue?

**Comment by phmagic** [comment]
Hi @apocal1pse, we have an S3 for testing and have not had this issue. Can you try to set your TTS to Google's default? http://en.kioskea.net/faq/33125-samsung-galaxy-s4-select-your-default-tts-engine
