### ISSUE TITLE
Unable to write parameters (Nexus 7)

### ISSUE THREAD

**Issue by LtDropkick** [DroidPlanner/droidplanner#1353]
Hi!

I use a Nexus 7 with Droiplanner 2 and wanted to fine tune the THR_MID setting today.

I can load the parameters from the copter.

I can select the parameter I want to change.

At this point the cursor jumps in front of the value I want to change and a numeric keyboard appears on screen.  I cannot delete the current value nor enter a new one.

Thanks for your work otherwise and hopefully you can help me resolve this problem!

**Comment by ne0fhyk** [comment]
@LtDropkick I'm guessing your nexus is running lollipop.
That issue was fixed, and the fix is available in the latest beta version.

**Comment by LtDropkick** [comment]
Thank you very much for your reply!
