### ISSUE TITLE
Install 3dr Service

### ISSUE THREAD

**Issue by ultrojo** [DroidPlanner/droidplanner#1370]
Installed latest Tower 3.x.13 , seems not complete because my Lenovo Android popup msg "Pls install 3dr service" which is redirect to Playstore and "not found"
Pls help

**Comment by ne0fhyk** [comment]
@ultrojo `3DR Services` is also in beta, so to install it, you need to join either the [mailing list](https://groups.google.com/forum/#!forum/3dr-services), or the [g+ community](https://plus.google.com/communities/109484130178804610965), and follow the instructions @  https://play.google.com/apps/testing/org.droidplanner.services.android
