### ISSUE TITLE
Reorder list of waypoint types in dropdown

### ISSUE THREAD

**Issue by phmagic** [DroidPlanner/droidplanner#1382]
* WayPoint
* Spline WayPoint
* Circle
* Region of Interest
* Change Speed
* Take off
* Land
* RTL
* Structure Scanner
* Camera Trigger
* EPM Gripper
* Set Yaw
* Set Servo

**Comment by ne0fhyk** [comment]
Fixed in commit c6698ba17f5fa977515e12da29ec1f1728d45c19
