### ISSUE TITLE
Clean up permissions

### ISSUE THREAD

**Issue by squilter** [DroidPlanner/droidplanner#1385]
Since the back-end is now handled by 3dr-services, I don't believe that Tower needs bluetooth, etc. anymore.

**Comment by ne0fhyk** [comment]
Could you list the permissions you think are not needed anymore. The bluetooth ones are still needed because Tower needs to be able to present the user with a list of available bluetooth devices.
Once a bluetooth device is selected, it passes it bt address to 3DR Services.

**Comment by squilter** [comment]
Scanning needs `BLUETOOTH_ADMIN`, but `BLUETOOTH` is for connecting.  Or does scanning need both of those?

Where are `ACCESS_NETWORK_STATE` and `ACCESS_WIFI_STATE` used?

**Comment by ne0fhyk** [comment]
`BLUETOOTH` is required to list paired bluetooth devices, while `BLUETOOTH_ADMIN` is required to discover and pair with new devices.
I'm investigating if we're still using `ACCESS_NETWORK_STATE` and `ACCESS_WIFI_STATE`.

**Comment by ne0fhyk** [comment]
`ACCESS_NETWORK_STATE` is used by the google maps api.
And `ACCESS_WIFI_STATE` will be used in the future to help with offline maps caching.
