### ISSUE TITLE
Droidplanner 3 (Tower) RC9 Pixhawk output changes with flight mode

### ISSUE THREAD

**Issue by Bradatech** [DroidPlanner/droidplanner#1394]
I have some interesting behavior with Tower.  I've got a gimbal connected to RC9 on a Pixhawk which has the tilt configured on channel 6 as described on the wiki for Follow Me and ROI to work.  Works great on DP2 but DP3, any changes to the flight mode will cause the gimbal to point straight ahead (horizon) and then lock in place (cannot control the tilt manually through radio channel 6) until I switch modes again.  Then I can change the tilt manually just fine.  This is in DISARMED mode.  Haven't flown it yet on DP3.

Running AC3.2 latest build.

![params](https://cloud.githubusercontent.com/assets/7535226/6142003/5f9e3fb8-b17c-11e4-971e-d4589574d70f.jpg)
![gimbal](https://cloud.githubusercontent.com/assets/7535226/6142002/5f9bcfbc-b17c-11e4-879a-f8c2f961129b.jpg)

**Comment by rmackay9** [comment]
Could you check what your MNT_MODE is when you connect?
It should be "3" normally which means under RC control.  Maybe it's somehow been set to "4" or some other number.

**Comment by ne0fhyk** [comment]
@Bradatech as mentioned in #1406, the issue you encountered was fixed in  [`3DR Services version 1.2.9`](https://github.com/DroidPlanner/3DRServices/pull/63).

**Comment by Bradatech** [comment]
@rmackay9 Randy, the value is 3.

@ne0fhyk Fredia, nice work!  all is well with the gimbal now.  The 3DR services update came through this morning via GooglePlay. Also, the Android Wear portion is now connecting and works very well.

Great job to you guys and the dev group.  The Pixhawk's future looks very promising and can't wait for optical flow :)
