### ISSUE TITLE
Survey in edit mode won't complete.  Markers remain red

### ISSUE THREAD

**Issue by Bradatech** [DroidPlanner/droidplanner#1395]
This is DP3 Beta (Tower).

I cannot move past drawing the survey region and selecting a camera and altitude.  The altitude remains red and no way to get the grid to appear so I can upload the mission.  Any ideas?﻿

**Comment by PaulHam211** [comment]
Where is survey mode now? in DP2 i could draw over the map and it makes a grid which the angle can be changed. has this feature been removed from tower?

**Comment by Bradatech** [comment]
This is fixed in v1.2.8  please close
