### ISSUE TITLE
Dronie broken?

### ISSUE THREAD

**Issue by tneuber** [DroidPlanner/droidplanner#1402]
I can push the button. Nothing happens. No mission, no message.
It 's working for me with the old Droidplanner.

**Comment by ne0fhyk** [comment]
@tneuber you may have `Dronie disabled` saved as a preference.
Navigate to `Settings` -> `User Interface` -> `Preference Dialogs` and check the preference for the `Create dronie?` item.

**Comment by tneuber** [comment]
Hi, thanks for your quick help. you're right. It works now.
