### ISSUE TITLE
Add antenna tracker support

### ISSUE THREAD

**Issue by alextel69** [DroidPlanner/droidplanner#1409]
When flying long-range, one needs a special pointed antenna, which in turn requires an antenna tracker.
Possible firmware option is [ArduTracker] (https://github.com/diydrones/ardupilot/tree/master/AntennaTracker). It needs incoming MAVLink packets to be forwarded to it. It is run on Pixhawk and can stabilize antenna even in motion (mounted on top of a car, for instance).
Hardware side of tracker is plain old Pixhawk and a couple of servos.

**Comment by ne0fhyk** [comment]
@alextel69 For the moment, this is out of the scope of the planned features for the app.
