### ISSUE TITLE
When connected to a Rover the Connect icon doesn't change - it still says Connect.

### ISSUE THREAD

**Issue by gmorph** [DroidPlanner/droidplanner#1421]
When I connect to a plane the Connect icon changes to "Arm" however when I connect to my rover there isn't any change - it still says "Connect".  Can we update it to say "Disconnect" at the least?
Thanks, Grant

**Comment by ne0fhyk** [comment]
Fixed by PR #1427 . 
The update will be available in the `3.1.5 release`.
