### ISSUE TITLE
Moving mission items

### ISSUE THREAD

**Issue by zlite** [DroidPlanner/droidplanner#951]
Moving a mission item on the list doesn't have any effect on the uploaded mission, just changing the graphical interface.

The bug seams to have been introduced with the decoupling on the map interface, to add support for the osm provider.

Original message:
>When you move an ROI waypoint from the end of a list of waypoints to the beginning, where it belongs, the ROI function doesn't function as if it were invoked at that point, so as a result it doesn't work at all. (It also keeps the same waypoint number, which seems suboptimal)

**Comment by ne0fhyk** [comment]
Merged into #1356
